spring:
  application:
    name: Task-Time-Tracker

  datasource:
    url: jdbc:postgresql://localhost:5400/task_tracker
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always

server:
  port: 8081

mybatis:
  configuration:
    map-underscore-to-camel-case: true